version: "2"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
