version: "2"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
  pgsql:
    image: "postgres:15"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    environment:
      PGPASSWORD: "secret"
      POSTGRES_DB: "shuttle_catalog"
      POSTGRES_USER: "work_wheel"
      POSTGRES_PASSWORD: "secret"
    volumes:
      - "sail-pgsql:/var/lib/postgresql/data"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "shuttle_catalog"
        - "-U"
        - "work_wheel"
      retries: 3
      timeout: 5s
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: work_wheel
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_URL: mongodb://work_wheel:secret@mongo:27017/

volumes:
  sail-pgsql:
    driver: local
